version: 2.1

executors:
  app:
    working_directory: /src

    docker:
      - image: node:alpine

commands:
  setup:
    steps:
      - run:
          name: Setup Container
          command: "apk add --update --no-cache ca-certificates git openssh g++ make python"

  persist:
    steps:
      - persist_to_workspace: { root: /src, paths: . }

  attach:
    steps:
      - attach_workspace: { at: "." }

  npmrc:
    steps:
      - run:
          name: Setup .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

  install:
    steps:
      - npmrc

      - run:
          name: Install dependencies
          command: npm ci

jobs:
  build:
    executor: app
    steps:
      - setup
      - checkout
      - install
      - persist

  lint:
    executor: app
    steps:
      - attach
      - run: npm run lint

  release:
    executor: app
    steps:
      - setup
      - npmrc
      - attach
      - run: npx semantic-release

workflows:
  version: 2
  run:
    jobs:
      - build:
          context: npm-library

      - lint:
          requires: [ build ]

      - release:
          context: npm-library
          requires: [ build, lint ]
          filters:
            branches:
              only: master
